// filename: console/src/utils/quotes.ts
export const inspirationalQuotes = [
  "Efficiency is doing better what is already being done.",
  "Quality systems produce great results.",
  "Data is the new oil—refine it wisely.",
  "Success is built on consistency and innovation.",
  "Monitor the process, master the outcome.",
  "The clearer the data, the better the decisions.",
  "Automation is the heartbeat of modern productivity.",
  "Small tweaks in systems yield big results.",
  "Precision engineering starts with measured intelligence.",
  "Caring for others is the foundation of great societies.",
  "What gets measured gets improved.",
  "Reliable systems make excellence repeatable.",
  "Without insight, data is just noise.",
  "Build with purpose; optimize with principle.",
  "The simplest solution is often the most elegant.",
  "Sustainable progress comes from disciplined iteration.",
  "Order emerges through thoughtful design.",
  "Every constraint is an opportunity for innovation.",
  "Are you on the controls team at VTR? Because you just fed the perfect signal to my heart.",
  "Every stable system is an echo of principled design.",
  "Intelligence is not speed, but the calibration of response.",
  "Refinement is the art of eliminating the unnecessary.",
  "Systems fail at their weakest point—strengthen the invisible.",
  "The invisible architecture determines the visible performance.",
  "A good metric reveals more than it measures.",
  "True innovation harmonizes beauty, efficiency, and function.",
  "Data without context is potential unrealized.",
  "The most powerful systems serve quietly and endure."
];
